version: '3.7'

services:
    nginx-ssl:
        image: nginx:latest
        restart: always
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/certs:/etc/nginx/certs
        ports:
            - "80:80"
            - "443:443"

    php:
        build: ./docker/php/
        restart: always
        volumes:
            - .:/var/www/html
        environment:
            - "MYSQL_PORT=3306"

    mysql:
        image: mysql:5.6
        restart: always
        volumes:
            - .:/var/www/html
            - ./db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=project
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        ports:
            - "3306:3306"
