version: '3'

services:
    nginx-ssl:
        image: nginx:latest
        volumes:
            - ./www:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/certs:/usr/local/share/ca-certificates
        depends_on:
            - php
        ports:
            - "81:80"
            - "444:443"

    php:
        build: ./docker/php/
        volumes:
            - ./www:/var/www/html
        environment:
            - "MYSQL_PORT=3308"

    mysql:
        image: mysql:5.6
        volumes:
            - .:/var/www/html
            - ./db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=project
        ports:
            - "3308:3306"
