version: '3.7'

services:
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - mysql
          - php

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html

    mysql:
        image: mysql:5.6
        expose:
            - 3306
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: project
